version: '2'
services:
  lt_dombo:
    image: botusau/lt_dombo:v1.0.0
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - SENTENCE_TRANSFORMERS_HOME=/data/nlp_cache
      - TRANSFORMERS_CACHE=/data/nlp_cache
    volumes:
      - models_data:/data/models
      - nlp_cache_data:/data/nlp_cache

volumes:
  models_data:
  nlp_cache_data:
